on: push
name: Clippy Check
jobs:
  axtc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy

      - name: Check axtc
        run: cargo clippy --all-features -- -Dwarnings
